name: boiler_plate_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl: ^0.18.1
  json_to_model: ^3.2.4
  quiver: ^3.2.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_screenutil: 5.9.0
  firebase_core: 2.16.0
  cloud_firestore: 4.9.2
  fluttertoast: 8.2.2
  confirm_dialog: 1.0.2
  shared_preferences: 2.2.1
  flutter_native_splash: 2.3.2
  control_style: 0.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  color_dark: '#ffffff'
  image: assets/images/me.png
  android_12: 
    color: '#ffffff'
    color_dark: '#2E398F'
    icon_background_color_dark: '#2E398F'
    image: assets/images/me.png
    image_dark: assets/images/me.png
  fullscreen: true

