// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLU-1aDi-1d9BdTTnV7wUaDbvUi1KR9c',
    appId: '1:192805094338:web:6624efc05c507da0b20c5b',
    messagingSenderId: '192805094338',
    projectId: 'netzme-e435c',
    authDomain: 'netzme-e435c.firebaseapp.com',
    storageBucket: 'netzme-e435c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeva43_In16U94gncdDBHCfxtVnAK31OA',
    appId: '1:192805094338:android:0753e9be86972e4cb20c5b',
    messagingSenderId: '192805094338',
    projectId: 'netzme-e435c',
    storageBucket: 'netzme-e435c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8kLvzK4HyJ8K-RbgC5wcKdZh0gYXY58',
    appId: '1:192805094338:ios:2014d70b99e6e97cb20c5b',
    messagingSenderId: '192805094338',
    projectId: 'netzme-e435c',
    storageBucket: 'netzme-e435c.appspot.com',
    iosBundleId: 'com.bayuleo.getx.boilerPlateGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH8kLvzK4HyJ8K-RbgC5wcKdZh0gYXY58',
    appId: '1:192805094338:ios:8cbb9831ee199705b20c5b',
    messagingSenderId: '192805094338',
    projectId: 'netzme-e435c',
    storageBucket: 'netzme-e435c.appspot.com',
    iosBundleId: 'com.bayuleo.getx.boilerPlateGetx.RunnerTests',
  );
}
